services:
  - type: web
    name: asdf-api
    env: node
    startCommand: npm start
    buildCommand: npm install
    plan: free
    envVars: []
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASS
        sync: false
